LIONOS_TARGET = lionos
LIONOS_OBJ_DIR = ${SRC_DIR}/${LIONOS_TARGET}
LIONOS_LIB_PATH = ${LIB_PATH}/${LIONOS_TARGET}

#源文件
LIONOS_SOURCE = $(LIONOS_OBJ_DIR)/lyos.c
#中间文件
LIONOS_OBJS = $(patsubst %.c, %.o, $(LIONOS_SOURCE))

#安装依赖
INSTALL_DEPS += install-$(LIONOS_TARGET)


LIONOS_LIB = ${LIONOS_TARGET}

ifeq (${PLAT}, win32)
	LIONOS_LIB =  ${LIONOS_LIB_PATH}/${LIONOS_TARGET}.dll
else
	LIONOS_LIB =  ${LIONOS_LIB_PATH}/${LIONOS_TARGET}.so
endif

#添加进全局目标集合
TARGETS += ${LIONOS_LIB}

OBJS += ${LIONOS_OBJS}

${LIONOS_LIB}: ${LIONOS_OBJS} $(BASE_OBJS)
	-$(MKDIR) $(LIONOS_LIB_PATH)
	${CC} -o ${LIONOS_LIB} $^ ${LDFLAGS}

install-lionos:
	-$(MKDIRALL) $(INSTALLDIR)/$(LIONOS_TARGET)/
	-$(CP) $(LIONOS_LIB_PATH)/$(LIONOS_TARGET).* $(INSTALLDIR)/$(LIONOS_TARGET)/
